# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: minimal folio
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site

# -----------------------------------------------------------------------------
# Build settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-paginate-v2
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock

# Pagination
pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

twitter_username: twitter_username
github_username:  github_username

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Plug-ins
plugins:
  - jekyll-paginate-v2
